<a href="https://colab.research.google.com/github/MobileApplicationBeraldi/Queues/blob/main/MDP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

transition probability matrix
$P=
\begin{pmatrix}
q_A q_B & q_Ap_B & 0 & 0 & p_A & 0\\
p_{EB}q_Aq_B & p_{12} & q_A p_B & 0 & p_A & 0   \\
p^2_{EB} q_B q_A& 2 p_{EB} q_{EB}q_Bq_A & p_{22} & q_A p_B & 0 & p_A   \\
p^3_{EB} & 3 p^2_{EB} q_{EB}& 3 p_{EB} q^2_{B} & p_{33} & 0 & 0   \\
q_{EA} q_B & 0 & p_{EB} q_{B} & 0 & p_{44} & p_B   \\
p_{EB} p_{EB} & p_{EA} q_{EB} & 0 & 0 & p_{EB} q_{EA} & p_{55}   \end{pmatrix}
$




Reward matrix\
$R=\begin{pmatrix}
0 & 0 & 0 & 0 & 0 & 0\\
0 & 1 & 0 & 0 & 0 & 0\\
0 & 0 & 2 & 0 & 0 & 0\\
0 & 0 & 0 & 3 & 0 & 0\\
0 & 0 & 0 & 0 & 2 & 0\\
0 & 0 & 0 & 0 & 0 & 3
\end{pmatrix}
$

In [1]:
import numpy as np

pA=0.1;qA=1-pA #ARRIVAL PROBABILITY OF TYPE A USER
pEA=0.1;qEA=1-pEA#EXIT PROBABILIRT OF TYPE A USER
pB=0.2;qB=1-pB #ARRIVAL PROBABILITY OF TYPE B USER
pEB=0.2;qEB=1-pEB#EXIT PROBABILITY OF TYPE B USER

p = np.zeros((1,6)) #STEADY-STATE PROBABILITY VECTOR

p[0,0]=1

P = np.zeros((6, 6)) #TRANSITION PROB MATRIX


P[0,1]=qA*pB;P[0,4]=pA;P[0,0]=qA*qB

P[1,0]=pEB*qA*qB
P[1,2]=qA*pB
P[1,4]=pA
P[1,1]=1-sum(P[1])


P[2,0]= pEB*pEB*qB*qA
P[2,1]=2*pEB*qEB*qB*qA
P[2,3]=pB*qA
P[2,5]=pA
P[2,2]=1-sum(P[2])


P[3,2]=3*pEB*qEB*qEB
P[3,1]=3*pEB*pEB*qEB
P[3,0]=pEB*pEB*pEB
P[3,3]=1-sum(P[3])

P[4,0]=pEA*qB
P[4,2]=pEB*qB
P[4,5]=pB
P[4,4]=1-sum(P[4])


P[5,4]=pEB*qEA
P[5,1]=pEA*qEB
P[5,0]=pEA*pEB
P[5,5]=1-sum(P[5])


#print(P[1],sum(P[1]))
#print(sum(P[0]),sum(P[1]),sum(P[2]),sum(P[3]),sum(P[4]),sum(P[5]))

#FIRST OF ALL CHECK THE MC REACHES THE STEADY STATE...
for t in range(100):
  p = np.dot(p,P)
  #print(p[0],sum(p[0]))


R = np.zeros((6, 6)) #REWARD MATRIX
R[1,1]=1
R[2,2]=2
R[3,3]=3
R[4,4]=2
R[5,5]=3

#AVERAGE REWARD FROM ANY STATE
r = np.array([0,P[1,1],2*P[2,2],3*P[3,3],2*P[4,4],3*P[5,5]])


#print(p[0],r)


#TRY TO SOLVE DI MRP
v = np.array([0,0,0,0,0,0]) #STATE-VALUE FUNCTION

#print(v)

for i in range(1000):
  v=r+0.1*np.dot(P,v)
  print(v)


[0.     0.576  0.9216 1.536  1.12   2.16  ]
[0.021568   0.6369664  1.02658637 1.65556224 1.2406656  2.340288  ]
[0.02542495 0.64388505 1.03684592 1.66631784 1.25288096 2.35597158]
[0.02594934 0.64464593 1.03783963 1.66733199 1.2540737  2.35738374]
[0.02601272 0.64472713 1.03793684 1.6674298  1.25418883 2.35751402]
[0.02601989 0.64473562 1.03794644 1.66743937 1.25419995 2.35752625]
[0.02602067 0.64473649 1.03794739 1.66744032 1.25420102 2.35752741]
[0.02602076 0.64473658 1.03794748 1.66744041 1.25420113 2.35752753]
[0.02602076 0.64473659 1.03794749 1.66744042 1.25420114 2.35752754]
[0.02602077 0.64473659 1.03794749 1.66744042 1.25420114 2.35752754]
[0.02602077 0.64473659 1.03794749 1.66744042 1.25420114 2.35752754]
[0.02602077 0.64473659 1.03794749 1.66744042 1.25420114 2.35752754]
[0.02602077 0.64473659 1.03794749 1.66744042 1.25420114 2.35752754]
[0.02602077 0.64473659 1.03794749 1.66744042 1.25420114 2.35752754]
[0.02602077 0.64473659 1.03794749 1.66744042 1.25420114 2.35752754]
[0.0